sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t anil1977/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true anil1977/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-west-2-198789474472"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
