sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t anil1977/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true anil1977/docker-react npm run test


